# Generated by Django 4.1.1 on 2022-10-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currency", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="seq_number",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
