# Generated by Django 4.1.1 on 2022-10-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currency", "0002_data_seq_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="seq_number",
            field=models.IntegerField(),
        ),
    ]
