# Generated by Django 4.1.1 on 2022-09-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currency", "0002_alter_data_order_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="data",
            name="price_rub",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="data",
            name="price_usd",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
