# Generated by Django 4.1.1 on 2022-10-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currency", "0003_alter_data_seq_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="price_rub",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
