# Generated by Django 4.1.1 on 2022-10-03 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currency", "0004_data_price_rub"),
    ]

    operations = [
        migrations.AddField(
            model_name="data",
            name="notification_recevied",
            field=models.BooleanField(default=False),
        ),
    ]
