# Generated by Django 4.1.1 on 2022-10-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Data",
            fields=[
                ("seq_number", models.IntegerField()),
                (
                    "order_number",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("price_usd", models.DecimalField(decimal_places=2, max_digits=8)),
                ("price_rub", models.DecimalField(decimal_places=2, max_digits=10)),
                ("delivery_date", models.DateField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
